services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - FRONTEND_URL=http://localhost:3000
    volumes:
      # Hot reload dla backend (jeśli chcesz)
      - ./backend:/app
      - /app/node_modules
    networks:
      - k6-network

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend.dev
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:4000/api
      - DOCKER_ENV=true
    volumes:
      # 🔥 HOT RELOAD - mapowanie źródeł
      - ./frontend:/app
      # 📦 Protect node_modules (używamy z kontenera)
      - /app/node_modules
      # 🎯 Protect dist folder  
      - /app/dist
    depends_on:
      - backend
    networks:
      - k6-network

networks:
  k6-network:
    driver: bridge