version: '3.8'

services:
  frontend:
    image: node:18-alpine
    container_name: k6-dashboard-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "80:3000"
    command: sh -c "npm install && npm start"
    environment:
      - REACT_APP_API_URL=http://localhost:4000/api
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
      - PORT=3000
    networks:
      - k6-dashboard-network

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
      args:
        - K6_TESTS_REPO_URL=${K6_TESTS_REPO_URL:-https://github.com/dar-kow/k6-tests.git}
    container_name: k6-dashboard-backend
    volumes:
      - ./backend:/app
      - k6-tests-volume:/k6-tests
      - ./results:/results
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - FRONTEND_URL=http://localhost
      - K6_TESTS_REPO_URL=${K6_TESTS_REPO_URL:-https://github.com/dar-kow/k6-tests.git}
      - DEBUG=true
    networks:
      - k6-dashboard-network

volumes:
  k6-tests-volume:


networks:
  k6-dashboard-network:
    driver: bridge
